apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: frontend-pinned-class
  labels:
    scenario: 04-missing-zone-fallback
spec:
  nodePoolAutoCreation:
    enabled: true
  priorities:
  - machineFamily: m2  # Remediation: m2 is only available in us-east4-a and us-east4-b
  - machineFamily: n2  # Remediation: Add fallback machineFamily n2 compatible with us-east4-c to resolve stockouts
  - machineFamily: e2  # Remediation: Add fallback machineFamily e2 as cost-effective safety floor
  whenUnsatisfiable: DoNotScaleUp
