apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: db-hyperdisk-class
spec:
  nodePoolAutoCreation:
    enabled: true
  priorities:
    - machineFamily: c4
    - machineFamily: c3
    - machineFamily: n4
  whenUnsatisfiable: DoNotScaleUp
