apiVersion: v1
kind: ResourceQuota
metadata:
  name: baseline-tenant-quota
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "30"
    requests.cpu: "2"
    requests.memory: 4Gi
    services: "10"
